using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace repository_profilo.Models
{
    public partial class ExpQuestConsob
    {
        public string Ndg { get; set; }
        public string Data { get; set; }
        public string Ora { get; set; }
        public string Up { get; set; }
        public string Filiale { get; set; }
        public string Country { get; set; }
        public string Profilo { get; set; }
        public string Rischio { get; set; }
        public string Campo1 { get; set; }
        public string Campo2 { get; set; }
        public string Campo3 { get; set; }
        public string Campo4 { get; set; }
        public string Campo5 { get; set; }
        public string Campo6 { get; set; }
        public string Campo7 { get; set; }
        public string Campo8 { get; set; }
        public string Campo9 { get; set; }
        public string Campo10 { get; set; }
        public string Campo11 { get; set; }
        public string Campo12 { get; set; }
        public string Campo13 { get; set; }
        public string Campo14 { get; set; }
        public string Campo15 { get; set; }
        public string Campo16 { get; set; }
        public string Campo17 { get; set; }
        public string Campo18 { get; set; }
        public string Campo19 { get; set; }
        public string Campo20 { get; set; }
        public string Campo21 { get; set; }
        public string Campo22 { get; set; }
        public string Campo23 { get; set; }
        public string Campo24 { get; set; }
        public string Campo25 { get; set; }
        public string Campo26 { get; set; }
        public string Campo27 { get; set; }
        public string Campo28 { get; set; }
        public string Campo29 { get; set; }
        public string Campo30 { get; set; }
        public string Campo31 { get; set; }
        public string Campo32 { get; set; }
        public string Campo33 { get; set; }
        public string Campo34 { get; set; }
        public string Campo35 { get; set; }
        public string Campo36 { get; set; }
        public string Campo37 { get; set; }
        public string Campo38 { get; set; }
        public string Campo39 { get; set; }
        public string Campo40 { get; set; }
        public string Campo41 { get; set; }
        public string Campo42 { get; set; }
        public string Campo43 { get; set; }
        public string Campo44 { get; set; }
        public string Campo45 { get; set; }
        public string Campo46 { get; set; }
        public string Campo47 { get; set; }
        public string Campo48 { get; set; }
        public string Campo49 { get; set; }
        public string Campo50 { get; set; }
        public string Campo51 { get; set; }
        public string Campo52 { get; set; }
        public string Campo53 { get; set; }
        public string Campo54 { get; set; }
        public string Campo55 { get; set; }
        public string Campo56 { get; set; }
        public string Campo57 { get; set; }
        public string Campo58 { get; set; }
        public string Campo59 { get; set; }
        public string Campo60 { get; set; }
        public string Campo61 { get; set; }
        public string Campo62 { get; set; }
        public string Campo63 { get; set; }
        public string Campo64 { get; set; }
        public string Campo65 { get; set; }
        public string Campo66 { get; set; }
        public string Campo67 { get; set; }
        public string Campo68 { get; set; }
        public string Campo69 { get; set; }
        public string Campo70 { get; set; }
        public string Campo71 { get; set; }
        public string Campo72 { get; set; }
        public string Campo73 { get; set; }
        public string Campo74 { get; set; }
        public string Campo75 { get; set; }
        public string Campo76 { get; set; }
        public string Campo77 { get; set; }
        public string Campo78 { get; set; }
        public string Campo79 { get; set; }
        public string Campo80 { get; set; }
        public string Campo81 { get; set; }
        public string Campo82 { get; set; }
        public string Campo83 { get; set; }
        public string Campo84 { get; set; }
        public string Campo85 { get; set; }
        public string Campo86 { get; set; }
        public string Campo87 { get; set; }
        public string Campo88 { get; set; }
        public string Campo89 { get; set; }
        public string Campo90 { get; set; }
        public string Campo91 { get; set; }
        public string Campo92 { get; set; }
        public string Campo93 { get; set; }
        public string Campo94 { get; set; }
        public string Campo95 { get; set; }
        public string Campo96 { get; set; }
        public string Campo97 { get; set; }
        public string Campo98 { get; set; }
        public string Campo99 { get; set; }
        public string Campo100 { get; set; }
        public string Campo101 { get; set; }
        public string Campo102 { get; set; }
        public string Campo103 { get; set; }
        public string Campo104 { get; set; }
        public string Campo105 { get; set; }
        public string Campo106 { get; set; }
        public string Campo107 { get; set; }
        public string Campo108 { get; set; }
        public string Campo109 { get; set; }
        public string Campo110 { get; set; }
        public string Campo111 { get; set; }
        public string Campo112 { get; set; }
        public string Campo113 { get; set; }
        public string Campo114 { get; set; }
        public string Campo115 { get; set; }
        public string Campo116 { get; set; }
        public string Campo117 { get; set; }
        public string Campo118 { get; set; }
        public string Campo119 { get; set; }
        public string Campo120 { get; set; }
        public string Campo121 { get; set; }
        public string Campo122 { get; set; }
        public string Campo123 { get; set; }
        public string Campo124 { get; set; }
        public string Campo125 { get; set; }
        public string Campo126 { get; set; }
        public string Campo127 { get; set; }
        public string Campo128 { get; set; }
        public string Campo129 { get; set; }
        public string Campo130 { get; set; }
        public string Campo131 { get; set; }
    }
}
